using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Health.Data.Migrations
{
    public partial class db_add_users_and_roles : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Permissions",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    SystemName = table.Column<string>(type: "varchar(255)", maxLength: 255, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    Category = table.Column<string>(type: "varchar(255)", maxLength: 255, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Permissions", x => x.Id);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Roles",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    IsSystem = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    ParentRoleId = table.Column<long>(type: "bigint", nullable: false),
                    Name = table.Column<string>(type: "varchar(95)", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    NormalizedName = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    ConcurrencyStamp = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Roles", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Roles_Roles_ParentRoleId",
                        column: x => x.ParentRoleId,
                        principalTable: "Roles",
                        principalColumn: "Id");
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Description = table.Column<string>(type: "varchar(100)", maxLength: 100, nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    TeudatZehut = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    FirstName = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    LastName = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    PushToken = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    CreateUser = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    UpdateUser = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    UtcOffset = table.Column<TimeSpan>(type: "time", nullable: true),
                    UpdateDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    CreateDate = table.Column<DateTime>(type: "datetime", nullable: false),
                    UserName = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    NormalizedUserName = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    Email = table.Column<string>(type: "varchar(255)", maxLength: 255, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    NormalizedEmail = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    EmailConfirmed = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    PasswordHash = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    SecurityStamp = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    ConcurrencyStamp = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    PhoneNumber = table.Column<string>(type: "longtext", nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    PhoneNumberConfirmed = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "datetime", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "PermissionRoles",
                columns: table => new
                {
                    PermissionId = table.Column<long>(type: "bigint", nullable: false),
                    RoleId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PermissionRoles", x => new { x.PermissionId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_PermissionRoles_Permissions_PermissionId",
                        column: x => x.PermissionId,
                        principalTable: "Permissions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PermissionRoles_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "RoleDefaultClaimsValues",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    RoleId = table.Column<long>(type: "bigint", nullable: false),
                    ClaimType = table.Column<string>(type: "varchar(255)", maxLength: 255, nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    DefaultValue = table.Column<string>(type: "varchar(1500)", maxLength: 1500, nullable: true)
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RoleDefaultClaimsValues", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RoleDefaultClaimsValues_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "UserRoles",
                columns: table => new
                {
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    RoleId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_UserRoles_Roles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "Roles",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_UserRoles_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id");
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.InsertData(
                table: "Permissions",
                columns: new[] { "Id", "Category", "Name", "SystemName" },
                values: new object[,]
                {
                    { 1L, "Standard", "Access admin area", "AccessAdminPanel" },
                    { 2L, "Platform", "Access Platform Settings", "AccessPlatformSettings" },
                    { 3L, "Platform", "Edit Platform Settings", "EditPlatformSettings" },
                    { 4L, "Platform", "Access Platform Reporting", "AccessPlatformReporting" },
                    { 5L, "Users", "Access Users", "AccessUsers" },
                    { 6L, "Users", "Edit Users", "EditUsers" },
                    { 7L, "Users", "Create Users", "CreateUsers" },
                    { 8L, "Users", "Delete Users", "DeleteUsers" },
                    { 9L, "Users", "Access Platform Maintenance", "AccessPlatformMaintenance" },
                    { 10L, "Users", "Access Localization Managment", "AccessLocalizationManagment" },
                    { 11L, "Agencies", "Access Agencies", "AccessAgencies" },
                    { 12L, "Agencies", "Create Agencies", "CreateAgencies" },
                    { 13L, "Agencies", "Edit Agencies", "EditAgencies" },
                    { 14L, "Agencies", "Delete Agencies", "DeleteAgencies" },
                    { 15L, "Platform", "Access Platform Communications", "AccessPlatformCommunications" },
                    { 16L, "CarModelConfiguration", "Access Platform Car Model Configuration", "AccessPlatformCarModelConfiguration" },
                    { 17L, "CarModelConfiguration", "Edit Platform Car Model Configuration", "EditPlatformCarModelConfiguration" },
                    { 18L, "CarModelConfiguration", "Create Platform Car Model Configuration", "CreatePlatformCarModelConfiguration" },
                    { 19L, "CarModelConfiguration", "Delete Platform Car Model Configuration", "DeletePlatformCarModelConfiguration" },
                    { 20L, "Agencies", "Access Agency Fleet", "AccessAgencyFleet" },
                    { 21L, "Agencies", "Edit Agency Fleet", "EditAgencyFleet" },
                    { 22L, "Agencies", "Create Agency Fleet", "CreateAgencyFleet" },
                    { 23L, "Agencies", "Delete Agency Fleet", "DeleteAgencyFleet" },
                    { 24L, "Agencies", "Access Agency Fleet Services", "AccessAgencyFleetServices" },
                    { 25L, "Agencies", "Edit Agency Fleet Services", "EditAgencyFleetServices" },
                    { 26L, "Agencies", "Create Agency Fleet Services", "CreateAgencyFleetServices" },
                    { 27L, "Agencies", "Delete Agency Fleet Services", "DeleteAgencyFleetServices" },
                    { 28L, "Agencies", "Access Agency Fleet Parkings", "AccessAgencyFleetParkings" },
                    { 29L, "Agencies", "Edit Agency Fleet Parkings", "EditAgencyFleetParkings" },
                    { 30L, "Agencies", "Create Agency Fleet Parkings", "CreateAgencyFleetParkings" },
                    { 31L, "Agencies", "Delete Agency Fleet Parkings", "DeleteAgencyFleetParkings" },
                    { 32L, "Agencies", "Access Agency Fleet Segments", "AccessAgencyFleetSegments" },
                    { 33L, "Agencies", "Edit Agency Fleet Segments", "EditAgencyFleetSegments" },
                    { 34L, "Agencies", "Create Agency Fleet Segments", "CreateAgencyFleetSegments" },
                    { 35L, "Agencies", "Delete Agency Fleet Segments", "DeleteAgencyFleetSegments" },
                    { 36L, "Agencies", "Access Agency Fleet Inventories", "AccessAgencyFleetInventories" },
                    { 37L, "Agencies", "Edit Agency Fleet Inventories", "EditAgencyFleetInventories" },
                    { 38L, "Agencies", "Create Agency Fleet Inventories", "CreateAgencyFleetInventories" },
                    { 39L, "Agencies", "Delete Agency Fleet Inventories", "DeleteAgencyFleetInventories" },
                    { 40L, "Agencies", "Access Agency Vehicle OnBoarding", "AccessAgencyVehicleOnBoarding" },
                    { 41L, "Vehicles", "Access Agency Vehicles", "AccessAgencyVehicles" },
                    { 42L, "Vehicles", "Edit Agency Vehicles", "EditAgencyVehicles" },
                    { 43L, "Vehicles", "Create Agency Vehicles", "CreateAgencyVehicles" },
                    { 44L, "Vehicles", "Delete Agency Vehicles", "DeleteAgencyVehicles" },
                    { 45L, "Localization", "Access Localization", "AccessLocalization" },
                    { 46L, "Localization", "Edit Localization", "EditLocalization" },
                    { 47L, "Localization", "Create Localization", "CreateLocalization" },
                    { 48L, "Localization", "Delete Localization", "DeleteLocalization" },
                    { 49L, "Configuration", "Access Settings", "AccessSettings" },
                    { 50L, "Configuration", "Edit Settings", "EditSettings" },
                    { 51L, "Configuration", "Create Settings", "CreateSettings" },
                    { 52L, "Configuration", "Delete Settings", "DeleteSettings" },
                    { 53L, "Configuration", "Access Roles", "AccessRoles" },
                    { 54L, "Configuration", "Edit Roles", "EditRoles" },
                    { 55L, "Configuration", "Create Roles", "CreateRoles" },
                    { 56L, "Configuration", "Delete Roles", "DeleteRoles" },
                    { 57L, "Platform", "Access Alerts", "AccessAlerts" },
                    { 58L, "Platform", "Edit Alerts", "EditAlerts" },
                    { 59L, "Platform", "Create Alerts", "CreateAlerts" },
                    { 60L, "Platform", "Delete Alerts", "DeleteAlerts" },
                    { 61L, "Platform", "Access Tags", "AccessTags" },
                    { 62L, "Platform", "Edit Tags", "EditTags" },
                    { 63L, "Platform", "Create Tags", "CreateTags" },
                    { 64L, "Platform", "Delete Tags", "DeleteTags" },
                    { 65L, "Platform", "Access Bookings", "AccessBookings" },
                    { 66L, "Platform", "Edit Bookings", "EditBookings" },
                    { 67L, "Platform", "Create Bookings", "CreateBookings" },
                    { 68L, "Platform", "Delete Bookings", "DeleteBookings" },
                    { 73L, "Platform", "Access Invoices", "AccessInvoices" },
                    { 74L, "Platform", "Edit Invoices", "EditInvoices" },
                    { 75L, "Platform", "Create Invoices", "CreateInvoices" },
                    { 76L, "Platform", "Delete Invoices", "DeleteInvoices" },
                    { 77L, "Vehicles", "Access Car Actions Log", "AccessCarActionsLog" },
                    { 78L, "Vehicles", "Send Action To Agency Car", "SendActionToAgencyCar" },
                    { 79L, "Agencies", "Access Agency Bank Account", "AccessAgencyBankAccount" },
                    { 80L, "Agencies", "Edit Agency Bank Account", "EditAgencyBankAccount" },
                    { 81L, "Agencies", "Create Agency Bank Account", "CreateAgencyBankAccount" },
                    { 82L, "Agencies", "Delete Agency Bank Account", "DeleteAgencyBankAccount" },
                    { 83L, "Agencies", "Access Agency Contacts", "AccessAgencyContacts" },
                    { 84L, "Agencies", "Edit Agency Contacts", "EditAgencyContacts" },
                    { 85L, "Agencies", "Create Agency Contacts", "CreateAgencyContacts" },
                    { 86L, "Agencies", "Delete Agency Contacts", "DeleteAgencyContacts" },
                    { 87L, "Agencies", "Access Agency Users", "AccessAgencyUsers" },
                    { 88L, "Agencies", "Edit Agency Userss", "EditAgencyUsers" },
                    { 89L, "Agencies", "Create Agency Users", "CreateAgencyUsers" },
                    { 90L, "Agencies", "Delete Agency Users", "DeleteAgencyUsers" },
                    { 91L, "Platform", "Access Payment Plans", "AccessPaymentPlans" },
                    { 92L, "Platform", "Edit Payment Plans", "EditPaymentPlans" },
                    { 93L, "Platform", "Create Payment Plans", "CreatePaymentPlans" },
                    { 94L, "Platform", "Delete Payment Plans", "DeletePaymentPlans" },
                    { 95L, "Agencies", "Access Agency B2B Subsriptions", "AccessAgencyB2BSubsriptions" },
                    { 96L, "Agencies", "Edit Agency B2B Subsriptions", "EditAgencyB2BSubsriptions" },
                    { 97L, "Agencies", "Create Agency B2B Subsriptions", "CreateAgencyB2BSubsriptions" },
                    { 98L, "Agencies", "Delete Agency B2B Subsriptions", "DeleteAgencyB2BSubsriptions" },
                    { 99L, "Agencies", "Access Agency B2C Subsriptions", "AccessAgencyB2CSubsriptions" },
                    { 100L, "Agencies", "Edit Agency B2C Subsriptions", "EditAgencyB2CSubsriptions" },
                    { 101L, "Agencies", "Create Agency B2C Subsriptions", "CreateAgencyB2CSubsriptions" },
                    { 102L, "Agencies", "Delete Agency B2C Subsriptions", "DeleteAgencyB2CSubsriptions" },
                    { 103L, "Agencies", "Access Agency Ancillaries", "AccessAgencyAncillaries" },
                    { 104L, "Agencies", "Edit Agency Ancillaries", "EditAgencyAncillaries" },
                    { 105L, "Agencies", "Create Agency Ancillaries", "CreateAgencyAncillaries" },
                    { 106L, "Agencies", "Delete Agency Ancillaries", "DeleteAgencyAncillaries" },
                    { 107L, "Agencies", "Access Agency Ancillary Groups", "AccessAgencyAncillaryGroups" },
                    { 108L, "Agencies", "Edit Agency Ancillary Groups", "EditAgencyAncillaryGroups" },
                    { 109L, "Agencies", "Create Agency Ancillary Groups", "CreateAgencyAncillaryGroups" },
                    { 110L, "Agencies", "Delete Agency Ancillary Groups", "DeleteAgencyAncillaryGroups" },
                    { 111L, "Agencies", "Access Agency Discounts", "AccessAgencyDiscounts" },
                    { 112L, "Agencies", "Edit Agency Discounts", "EditAgencyDiscounts" },
                    { 113L, "Agencies", "Create Agency Discounts", "CreateAgencyDiscounts" },
                    { 114L, "Agencies", "Delete Agency Discounts", "DeleteAgencyDiscounts" },
                    { 115L, "Agencies", "Access Agency Charges", "AccessAgencyCharges" },
                    { 116L, "Agencies", "Edit Agency Charges", "EditAgencyCharges" },
                    { 117L, "Agencies", "Delete Agency Charges", "DeleteAgencyCharges" },
                    { 118L, "Vehicles", "Access Vehicle Damages", "AccessVehicleDamages" },
                    { 119L, "Vehicles", "Edit Vehicle Damages", "EditVehicleDamages" },
                    { 120L, "Vehicles", "Create Vehicle Damages", "CreateVehicleDamages" },
                    { 121L, "Vehicles", "Delete Vehicle Damages", "DeleteVehicleDamages" },
                    { 122L, "Vehicles", "Access Vehicle Accidents", "AccessVehicleAccidents" },
                    { 123L, "Vehicles", "Edit Vehicle Accidents", "EditVehicleAccidents" },
                    { 124L, "Vehicles", "Create Vehicle Accidents", "CreateVehicleAccidents" },
                    { 125L, "Vehicles", "Delete Vehicle Accidents", "DeleteVehicleAccidents" },
                    { 126L, "Agencies", "Access Agency Prices", "AccessAgencyPrices" },
                    { 127L, "Agencies", "Edit Agency Prices", "EditAgencyPrices" },
                    { 128L, "Agencies", "Create Agency Prices", "CreateAgencyPrices" },
                    { 129L, "Agencies", "Delete Agency Prices", "DeleteAgencyPrices" },
                    { 130L, "Agencies", "Access Agency Price Cars", "AccessAgencyPriceCars" },
                    { 131L, "Agencies", "Edit Agency Price Cars", "EditAgencyPriceCars" },
                    { 132L, "Agencies", "Create Agency Price Cars", "CreateAgencyPriceCars" },
                    { 133L, "Agencies", "Delete Agency Price Cars", "DeleteAgencyPriceCars" },
                    { 134L, "Agencies", "Access Vehicle Class Types", "AccessVehicleClassTypes" },
                    { 135L, "Agencies", "Edit Vehicle Class Types", "EditVehicleClassTypes" },
                    { 136L, "Agencies", "Create Vehicle Class Types", "CreateVehicleClassTypes" },
                    { 137L, "Agencies", "Delete Vehicle Class Types", "DeleteVehicleClassTypes" },
                    { 138L, "Agencies", "Access Vehicle Class Groups", "AccessVehicleClassGroups" },
                    { 139L, "Agencies", "Edit Vehicle Class Groups", "EditVehicleClassGroups" },
                    { 140L, "Agencies", "Create Vehicle Class Groups", "CreateVehicleClassGroups" },
                    { 141L, "Agencies", "Delete Vehicle Class Groups", "DeleteVehicleClassGroups" },
                    { 142L, "Vehicles", "Access Car Synthesis", "AccessCarSynthesis" },
                    { 143L, "Vehicles", "Edit Car Synthesis", "EditCarSynthesis" },
                    { 144L, "Vehicles", "Create Car Synthesiss", "CreateCarSynthesis" },
                    { 145L, "Vehicles", "Delete Car Synthesis", "DeleteCarSynthesis" },
                    { 146L, "Platform", "Access Orders", "AccessOrders" },
                    { 147L, "Platform", "Edit Orders", "EditOrders" },
                    { 148L, "Platform", "Create Orders", "CreateOrders" },
                    { 149L, "Platform", "Delete Orders", "DeleteOrders" },
                    { 150L, "Platform", "Access Notes", "AccessNotes" },
                    { 151L, "Platform", "Edit Notes", "EditNotes" },
                    { 152L, "Platform", "Create Notes", "CreateNotes" },
                    { 153L, "Platform", "Delete Notes", "DeleteNotes" },
                    { 154L, "Customers", "Access Payment Methods", "AccessPaymentMethods" },
                    { 155L, "Customers", "Edit Payment Methods", "EditPaymentMethods" },
                    { 156L, "Customers", "Create Payment Methods", "CreatePaymentMethods" },
                    { 157L, "Customers", "Delete Payment Methods", "DeletePaymentMethods" },
                    { 158L, "Customers", "Access Customers", "AccessCustomers" },
                    { 159L, "Customers", "Edit Customerss", "EditCustomers" },
                    { 160L, "Customers", "Create Customers", "CreateCustomers" },
                    { 161L, "Customers", "Delete Customers", "DeleteCustomers" },
                    { 162L, "Customers", "Customer Subscription Approval", "CustomerSubscriptionApproval" },
                    { 163L, "Customers", "Customer Subscription Change", "CustomerSubscriptionChange" },
                    { 164L, "Platform", "Refund Order", "RefundOrder" },
                    { 165L, "Platform", "Order Extra Charge", "OrderExtraCharge" },
                    { 167L, "Platform", "Access Dashboards", "AccessDashboards" },
                    { 168L, "Vehicles", "Edit Agency Vehicle Tags", "EditAgencyVehicleTags" },
                    { 169L, "Customers", "Edit Customer Tags", "EditCustomerTags" },
                    { 170L, "Vehicles", "Access Vehicle Media Items", "AccessVehicleMediaItems" },
                    { 171L, "Vehicles", "Edit Vehicle Media Items", "EditVehicleMediaItems" },
                    { 172L, "Vehicles", "Create Vehicle Media Items", "CreateVehicleMediaItems" },
                    { 173L, "Vehicles", "Delete Vehicle Media Items", "DeleteVehicleMediaItems" },
                    { 174L, "Vehicles", "Assign Car Zone", "AssignCarZone" },
                    { 175L, "Customers", "Lock Customer", "LockCustomer" },
                    { 176L, "Customers", "Unlock Customer", "UnlockCustomer" },
                    { 177L, "Configuration", "Access Log Activities", "AccessLogActivities" },
                    { 178L, "Platform", "Extend Order", "ExtendOrder" },
                    { 179L, "Platform", "Finalize Order", "FinalizeOrder" },
                    { 180L, "Customers", "Access Customer Accidents", "AccessCustomerAccident" },
                    { 181L, "Customers", "Edit Customer Accidents", "EditCustomerAccidents" },
                    { 182L, "Customers", "Create Customer Accidents", "CreateCustomerAccidents" },
                    { 183L, "Customers", "Delete Customer Accidents", "DeleteCustomerAccidents" },
                    { 184L, "Agencies", "Access Agency Document Items", "AccessAgencyDocumentItems" },
                    { 185L, "Agencies", "Edit Agency Document Items", "EditAgencyDocumentItems" },
                    { 186L, "Agencies", "Create Agency Document Items", "CreateAgencyDocumentItems" },
                    { 187L, "Agencies", "Delete Agency Document Items", "DeleteAgencyDocumentItems" },
                    { 188L, "Vehicles", "Access Car Availability", "AccessCarAvailability" },
                    { 189L, "Vehicles", "Edit Car Availability", "EditCarAvailability" },
                    { 190L, "Vehicles", "Create Car Availability", "CreateCarAvailability" },
                    { 191L, "Vehicles", "Delete Car Availability", "DeleteCarAvailability" },
                    { 192L, "Platform", "Order Additional Drivers", "OrderAdditionalDrivers" },
                    { 193L, "Platform", "Attach Driver To Order", "AttachDriverToOrder" },
                    { 194L, "Agencies", "Access Fleet Charges", "AccessFleetCharges" },
                    { 195L, "Agencies", "Access Fleet Vehicles", "AccessFleetVehicles" },
                    { 196L, "Customers", "Create Customer Coupon", "CreateCustomerCoupons" },
                    { 197L, "Customers", "Access Customer Coupon", "AccessCustomerCoupons" },
                    { 198L, "Customers", "Edit Customer Coupon", "EditCustomerCoupons" },
                    { 199L, "Customers", "Delete Customer Coupon", "DeleteCustomerCoupons" },
                    { 200L, "Agencies", "Create Agency Coupon", "CreateAgencyCoupons" },
                    { 201L, "Agencies", "Access Agency Coupon", "AccessAgencyCoupons" },
                    { 202L, "Agencies", "Edit Agency Coupon", "EditAgencyCoupons" },
                    { 203L, "Agencies", "Delete Agency Coupon", "DeleteAgencyCoupons" },
                    { 204L, "Agencies", "Assign Fleet Subscriptions", "AssignFleeetSubscriptions" },
                    { 205L, "Agencies", "Assign Fleet Discounts", "AssignFleeetDiscounts" },
                    { 206L, "Agencies", "Assign Fleet Fixed Discounts", "AssignFleeetFixedDiscounts" },
                    { 207L, "Agencies", "Assign Fleet Charges", "AssignFleeetCharges" },
                    { 208L, "Agencies", "Assign Fleet Ancillaries", "AssignFleeetAncillaries" },
                    { 209L, "Agencies", "Assign Fleet Prices", "AssignFleeetPrices" },
                    { 210L, "Agencies", "Create Agency Charges", "CreateAgencyCharges" },
                    { 211L, "Agencies", "Access Dynamic Price", "AccessDynamicPrice" },
                    { 212L, "Agencies", "Edit Dynamic Price", "EditDynamicPrice" },
                    { 213L, "Agencies", "Create Dynamic Price", "CreateDynamicPrice" },
                    { 214L, "Agencies", "Delete Dynamic Price", "DeleteDynamicPrice" },
                    { 215L, "Agencies", "Access Leads", "AccessLeads" },
                    { 216L, "Agencies", "Edit Leads", "EditLeads" },
                    { 217L, "Agencies", "Create Leads", "CreateLeads" },
                    { 218L, "Agencies", "Delete Leads", "DeleteLeads" },
                    { 219L, "Configuration", "Access Templates", "AccessTemplates" },
                    { 220L, "Configuration", "Edit Templates", "EditTemplates" },
                    { 221L, "Configuration", "Create Templates", "CreateTemplates" }
                });

            migrationBuilder.InsertData(
                table: "Roles",
                columns: new[] { "Id", "ConcurrencyStamp", "IsSystem", "Name", "NormalizedName", "ParentRoleId" },
                values: new object[,]
                {
                    { 1L, "0243815c-f161-43cf-b6b3-e423f1c2ef25", true, "Admin", "ADMIN", 0L },
                    { 2L, "411b90a7-1c35-4f18-b7aa-13ad6f6f70a2", true, "PartnerAdmin", "PARTNERADMIN", 0L },
                    { 3L, "268c7970-0d1f-4a24-b6a9-4c8a6230e565", true, "Customer", "CUSTOMER", 0L }
                });

            migrationBuilder.InsertData(
                table: "PermissionRoles",
                columns: new[] { "PermissionId", "RoleId" },
                values: new object[,]
                {
                    { 1L, 1L },
                    { 1L, 2L },
                    { 2L, 1L },
                    { 3L, 1L },
                    { 4L, 1L },
                    { 5L, 1L },
                    { 5L, 2L },
                    { 5L, 3L },
                    { 6L, 1L },
                    { 6L, 2L },
                    { 7L, 1L },
                    { 7L, 2L },
                    { 8L, 1L },
                    { 8L, 2L },
                    { 9L, 1L },
                    { 10L, 1L },
                    { 11L, 1L },
                    { 11L, 2L },
                    { 12L, 1L },
                    { 13L, 1L },
                    { 14L, 1L },
                    { 15L, 1L },
                    { 16L, 1L },
                    { 17L, 1L },
                    { 18L, 1L },
                    { 19L, 1L },
                    { 20L, 1L },
                    { 20L, 2L },
                    { 21L, 1L },
                    { 21L, 2L },
                    { 22L, 1L },
                    { 22L, 2L },
                    { 23L, 1L },
                    { 23L, 2L },
                    { 24L, 1L },
                    { 24L, 2L },
                    { 25L, 1L },
                    { 25L, 2L },
                    { 26L, 1L },
                    { 26L, 2L },
                    { 27L, 1L },
                    { 27L, 2L },
                    { 28L, 1L },
                    { 28L, 2L },
                    { 29L, 1L },
                    { 29L, 2L },
                    { 30L, 1L },
                    { 30L, 2L },
                    { 31L, 1L },
                    { 31L, 2L },
                    { 32L, 1L },
                    { 32L, 2L },
                    { 33L, 1L },
                    { 33L, 2L },
                    { 34L, 1L },
                    { 34L, 2L },
                    { 35L, 1L },
                    { 35L, 2L },
                    { 36L, 1L },
                    { 36L, 2L },
                    { 37L, 1L },
                    { 37L, 2L },
                    { 38L, 1L },
                    { 38L, 2L },
                    { 39L, 1L },
                    { 39L, 2L },
                    { 40L, 1L },
                    { 40L, 2L },
                    { 41L, 1L },
                    { 41L, 2L },
                    { 42L, 1L },
                    { 42L, 2L },
                    { 43L, 1L },
                    { 43L, 2L },
                    { 44L, 1L },
                    { 44L, 2L },
                    { 45L, 1L },
                    { 46L, 1L },
                    { 47L, 1L },
                    { 48L, 1L },
                    { 49L, 1L },
                    { 49L, 2L },
                    { 50L, 1L },
                    { 50L, 2L },
                    { 51L, 1L },
                    { 51L, 2L },
                    { 52L, 1L },
                    { 52L, 2L },
                    { 53L, 1L },
                    { 53L, 2L },
                    { 54L, 1L },
                    { 54L, 2L },
                    { 55L, 1L },
                    { 55L, 2L },
                    { 56L, 1L },
                    { 56L, 2L },
                    { 57L, 1L },
                    { 57L, 2L },
                    { 58L, 1L },
                    { 58L, 2L },
                    { 59L, 1L },
                    { 59L, 2L },
                    { 60L, 1L },
                    { 60L, 2L },
                    { 61L, 1L },
                    { 61L, 2L },
                    { 62L, 1L },
                    { 62L, 2L },
                    { 63L, 1L },
                    { 63L, 2L },
                    { 64L, 1L },
                    { 64L, 2L },
                    { 65L, 1L },
                    { 65L, 2L },
                    { 66L, 1L },
                    { 66L, 2L },
                    { 67L, 1L },
                    { 67L, 2L },
                    { 67L, 3L },
                    { 68L, 1L },
                    { 68L, 2L },
                    { 73L, 1L },
                    { 73L, 2L },
                    { 74L, 1L },
                    { 74L, 2L },
                    { 75L, 1L },
                    { 75L, 2L },
                    { 76L, 1L },
                    { 76L, 2L },
                    { 77L, 1L },
                    { 77L, 2L },
                    { 78L, 1L },
                    { 78L, 2L },
                    { 79L, 1L },
                    { 79L, 2L },
                    { 80L, 1L },
                    { 80L, 2L },
                    { 81L, 1L },
                    { 81L, 2L },
                    { 82L, 1L },
                    { 82L, 2L },
                    { 83L, 1L },
                    { 83L, 2L },
                    { 84L, 1L },
                    { 84L, 2L },
                    { 85L, 1L },
                    { 85L, 2L },
                    { 86L, 1L },
                    { 86L, 2L },
                    { 87L, 1L },
                    { 87L, 2L },
                    { 88L, 1L },
                    { 88L, 2L },
                    { 89L, 1L },
                    { 89L, 2L },
                    { 90L, 1L },
                    { 90L, 2L },
                    { 91L, 1L },
                    { 91L, 2L },
                    { 92L, 1L },
                    { 93L, 1L },
                    { 94L, 1L },
                    { 94L, 2L },
                    { 95L, 1L },
                    { 95L, 2L },
                    { 96L, 1L },
                    { 96L, 2L },
                    { 97L, 1L },
                    { 97L, 2L },
                    { 98L, 1L },
                    { 98L, 2L },
                    { 99L, 1L },
                    { 99L, 2L },
                    { 100L, 1L },
                    { 100L, 2L },
                    { 101L, 1L },
                    { 101L, 2L },
                    { 102L, 1L },
                    { 102L, 2L },
                    { 103L, 1L },
                    { 103L, 2L },
                    { 104L, 1L },
                    { 104L, 2L },
                    { 105L, 1L },
                    { 105L, 2L },
                    { 106L, 1L },
                    { 106L, 2L },
                    { 107L, 1L },
                    { 107L, 2L },
                    { 108L, 1L },
                    { 108L, 2L },
                    { 109L, 1L },
                    { 109L, 2L },
                    { 110L, 1L },
                    { 110L, 2L },
                    { 111L, 1L },
                    { 111L, 2L },
                    { 112L, 1L },
                    { 112L, 2L },
                    { 113L, 1L },
                    { 113L, 2L },
                    { 114L, 1L },
                    { 114L, 2L },
                    { 115L, 1L },
                    { 115L, 2L },
                    { 116L, 1L },
                    { 116L, 2L },
                    { 117L, 1L },
                    { 117L, 2L },
                    { 118L, 1L },
                    { 118L, 2L },
                    { 119L, 1L },
                    { 119L, 2L },
                    { 120L, 1L },
                    { 120L, 2L },
                    { 121L, 1L },
                    { 121L, 2L },
                    { 122L, 1L },
                    { 122L, 2L },
                    { 123L, 1L },
                    { 123L, 2L },
                    { 124L, 1L },
                    { 124L, 2L },
                    { 125L, 1L },
                    { 125L, 2L },
                    { 126L, 1L },
                    { 126L, 2L },
                    { 127L, 1L },
                    { 127L, 2L },
                    { 128L, 1L },
                    { 128L, 2L },
                    { 129L, 1L },
                    { 129L, 2L },
                    { 130L, 1L },
                    { 130L, 2L },
                    { 131L, 1L },
                    { 131L, 2L },
                    { 132L, 1L },
                    { 132L, 2L },
                    { 133L, 1L },
                    { 133L, 2L },
                    { 134L, 1L },
                    { 134L, 2L },
                    { 135L, 1L },
                    { 135L, 2L },
                    { 136L, 1L },
                    { 136L, 2L },
                    { 137L, 1L },
                    { 137L, 2L },
                    { 138L, 1L },
                    { 138L, 2L },
                    { 139L, 1L },
                    { 139L, 2L },
                    { 140L, 1L },
                    { 140L, 2L },
                    { 141L, 1L },
                    { 141L, 2L },
                    { 142L, 1L },
                    { 142L, 2L },
                    { 143L, 1L },
                    { 143L, 2L },
                    { 144L, 1L },
                    { 144L, 2L },
                    { 145L, 1L },
                    { 145L, 2L },
                    { 146L, 1L },
                    { 146L, 2L },
                    { 147L, 1L },
                    { 147L, 2L },
                    { 148L, 1L },
                    { 148L, 2L },
                    { 149L, 1L },
                    { 149L, 2L },
                    { 150L, 1L },
                    { 150L, 2L },
                    { 151L, 1L },
                    { 151L, 2L },
                    { 152L, 1L },
                    { 152L, 2L },
                    { 153L, 1L },
                    { 153L, 2L },
                    { 154L, 1L },
                    { 154L, 2L },
                    { 155L, 1L },
                    { 155L, 2L },
                    { 156L, 1L },
                    { 156L, 2L },
                    { 157L, 1L },
                    { 157L, 2L },
                    { 158L, 1L },
                    { 158L, 2L },
                    { 158L, 3L },
                    { 159L, 1L },
                    { 159L, 2L },
                    { 160L, 1L },
                    { 160L, 2L },
                    { 161L, 1L },
                    { 161L, 2L },
                    { 162L, 1L },
                    { 162L, 2L },
                    { 163L, 1L },
                    { 163L, 2L },
                    { 164L, 1L },
                    { 164L, 2L },
                    { 165L, 1L },
                    { 165L, 2L },
                    { 167L, 1L },
                    { 167L, 2L },
                    { 168L, 1L },
                    { 168L, 2L },
                    { 169L, 1L },
                    { 169L, 2L },
                    { 170L, 1L },
                    { 170L, 2L },
                    { 171L, 1L },
                    { 171L, 2L },
                    { 172L, 1L },
                    { 172L, 2L },
                    { 173L, 1L },
                    { 173L, 2L },
                    { 174L, 1L },
                    { 174L, 2L },
                    { 175L, 1L },
                    { 175L, 2L },
                    { 176L, 1L },
                    { 176L, 2L },
                    { 177L, 1L },
                    { 177L, 2L },
                    { 178L, 1L },
                    { 178L, 2L },
                    { 179L, 1L },
                    { 179L, 2L },
                    { 180L, 1L },
                    { 180L, 2L },
                    { 181L, 1L },
                    { 181L, 2L },
                    { 182L, 1L },
                    { 182L, 2L },
                    { 183L, 1L },
                    { 183L, 2L },
                    { 184L, 1L },
                    { 184L, 2L },
                    { 185L, 1L },
                    { 185L, 2L },
                    { 186L, 1L },
                    { 186L, 2L },
                    { 187L, 1L },
                    { 187L, 2L },
                    { 188L, 1L },
                    { 188L, 2L },
                    { 189L, 1L },
                    { 189L, 2L },
                    { 190L, 1L },
                    { 190L, 2L },
                    { 191L, 1L },
                    { 191L, 2L },
                    { 192L, 1L },
                    { 192L, 2L },
                    { 193L, 1L },
                    { 193L, 2L },
                    { 194L, 1L },
                    { 194L, 2L },
                    { 195L, 1L },
                    { 195L, 2L },
                    { 196L, 1L },
                    { 197L, 1L },
                    { 198L, 1L },
                    { 199L, 1L },
                    { 200L, 1L },
                    { 201L, 1L },
                    { 202L, 1L },
                    { 203L, 1L },
                    { 204L, 1L },
                    { 204L, 2L },
                    { 205L, 1L },
                    { 205L, 2L },
                    { 206L, 1L },
                    { 206L, 2L },
                    { 207L, 1L },
                    { 207L, 2L },
                    { 208L, 1L },
                    { 208L, 2L },
                    { 209L, 1L },
                    { 209L, 2L },
                    { 210L, 1L },
                    { 210L, 2L },
                    { 211L, 1L },
                    { 211L, 2L },
                    { 212L, 1L },
                    { 212L, 2L },
                    { 213L, 1L },
                    { 213L, 2L },
                    { 214L, 1L },
                    { 214L, 2L },
                    { 215L, 1L },
                    { 215L, 2L },
                    { 216L, 1L },
                    { 216L, 2L },
                    { 217L, 1L },
                    { 217L, 2L },
                    { 218L, 1L },
                    { 218L, 2L },
                    { 219L, 1L },
                    { 219L, 2L },
                    { 220L, 1L },
                    { 220L, 2L },
                    { 221L, 1L },
                    { 221L, 2L }
                });

            migrationBuilder.CreateIndex(
                name: "IX_PermissionRoles_RoleId",
                table: "PermissionRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "IX_RoleDefaultClaimsValues_RoleId",
                table: "RoleDefaultClaimsValues",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "IX_Roles_Name",
                table: "Roles",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Roles_ParentRoleId",
                table: "Roles",
                column: "ParentRoleId");

            migrationBuilder.CreateIndex(
                name: "IX_UserRoles_RoleId",
                table: "UserRoles",
                column: "RoleId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PermissionRoles");

            migrationBuilder.DropTable(
                name: "RoleDefaultClaimsValues");

            migrationBuilder.DropTable(
                name: "UserRoles");

            migrationBuilder.DropTable(
                name: "Permissions");

            migrationBuilder.DropTable(
                name: "Roles");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
